Migrate from kapt to KSP
Also update to kotlin 1.9.10, see
<https://stackoverflow.com/questions/77342860/how-to-resolve-the-gradle-build-error-java-lang-nosuchmethoderror>.

Change-Id: Iaf7b8af6f656b0acdc15361ecb2658c24e642f22